<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    // Fonction pour recupérer les derniers articles
    public function rfind()
    {
        $qb = $this->_em->createQueryBuilder();
        
        $qb->select('a')
           ->from('BlogBundle:Article', 'a')
           ->orderBy('a.date', 'DESC');
                  
        return  $qb->getQuery()
                    ->getResult();
        
    }
    
}
