blog_accueil:
    pattern:  /
    defaults: { _controller: BlogBundle:Blog:index }
blog_article_voir:
    pattern:  /article/voir/{$id}
    defaults: { _controller: BlogBundle:Blog:voir }
    requirements:
        id:  \d+
blog_article_ajouter:
    pattern:  /article/ajouter
    defaults: { _controller: BlogBundle:Blog:ajouter }
blog_article_modifier:
    pattern:  /article/modifier/{$id}
    defaults: { _controller: BlogBundle:Blog:voir }
    requirements:
        id:   \d+
blog_article_supprimer:
    pattern:  /article/supprimer/{$id}
    defaults: { _controller: BlogBundle:Blog:voir }
    requirements:
        id:     \d+

